# Generated by Django 5.0.6 on 2024-06-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('author_name', models.TextField(max_length=64)),
                ('birth_date', models.DateField()),
                ('country', models.TextField(max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'db_table': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('book_name', models.TextField(max_length=128)),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksandauthors.authors')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'db_table': 'Books',
            },
        ),
    ]
