# Generated by Django 5.0.6 on 2024-06-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksandauthors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='country',
            field=models.TextField(default=None, max_length=64),
        ),
    ]
